# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NeverStop' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NeverStop
   pod 'AFNetworking', '~> 3.1.0'
   pod 'Masonry', '~> 1.0.2'
   pod 'SDWebImage', '~> 3.8.2'
   pod 'MJRefresh', '~> 3.1.12'
   pod 'SDiPhoneVersion', '~> 1.1.2'
   pod 'UMengAnalytics', '~> 4.1.0'
   pod 'SVProgressHUD', '~> 2.0.3'
   pod 'MJExtension', '~> 3.0.13'
   pod 'MBProgressHUD', '~> 1.0.0'
   pod 'CocoaLumberjack', '~> 2.4.0'
   pod 'AMap3DMap'  #3D地图SDK
   #pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤用)
   pod 'AMapSearch' #搜索服务SDK 
   pod 'FMDB', '~> 2.6.2'
   pod 'FTPopOverMenu', '~> 1.2.1'
   pod 'HyphenateFullSDK', '~> 3.1.5'
end
